### PR TITLE
scripts: Fallback to IPv4 for spice if lo doesn't have an ipv6 addr

### PR DESCRIPTION
**Pull request by SludgeGirl**
Hey! Just a small patch to allow spice to fallback to IPv4 in cases where the user has disabled IPv6. I needed a bit of a break from the general Cockpit tests so thought it'd pick up a bug or two, but the tests are getting close!

### CODE REVIEW

File: src/scripts/install_machine.py [hunk 1]
```diff
@@ -54,11 +54,20 @@ def get_graphics_capabilies(connection):
...
 
 def prepare_graphics_params(connection):
+    # Use ipv6 as workaround for https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1492621
+    spice_address = '::1'
+    # Check to make sure loopback has an IPv6 address assigned
+    # if not default back to IPv4
+    ipv6_loopback = subprocess.check_output(['ip', '-6', 'addr'])
+
+    if not "lo:" in str(ipv6_loopback):
+        spice_address = '127.0.0.1'
```
Comment (martinpitt) [inline src/scripts/install_machine.py:64]: Can you please do `ip -6 addr show dev lo`? And make this robust against failures of the call? The `ip` utility may not be installed, or perhaps some other weird thing. We don't want the script to crash then.

**Review by martinpitt — CHANGES_REQUESTED** [review]
Thanks! The general approach looks fine, but let's robustify this a bit.

File: src/scripts/install_machine.py (hunk 1 above)
Comment (SludgeGirl) [reply src/scripts/install_machine.py]: Yep! Thanks for the review, I've just reworked it quite a bit to be more robust and check against ifconfig if ip doesn't exist. This should be alot more robust

**Comment by martinpitt** [comment]
Interesting this [breaks on rawhide](https://artifacts.dev.testing-farm.io/25a99126-da33-45da-a19f-0ae964f25e4c/):

```
    self.assertEqual(spice_listen, spice[0].attrib['listen'])
AssertionError: '::1' != '127.0.0.1'
- ::1
+ 127.0.0.1
```

So this overrides an explicit configuration in `/etc/libvirt/qemu.conf`, which we should never do. This should only change the implicit default. The code tries to do that, but I think I see the problem.

File: src/scripts/install_machine.py [hunk 2]
```diff
@@ -54,11 +54,35 @@ def get_graphics_capabilies(connection):
...
 
 def prepare_graphics_params(connection):
+    # Use ipv6 as workaround for https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1492621
+    spice_address = '::1'
+
+    # Check to make sure loopback has an IPv6 address assigned
+    # if not default back to IPv4
+    try:
+        if subprocess.run(['ip'], shell=True).returncode == 0:
+            ipv6_loopback = subprocess.check_output(['ip', '-6', 'addr', 'show', 'dev', 'lo'])
```
Comment (martinpitt) [inline src/scripts/install_machine.py:64]: Please avoid `shell=True` and running this command twice. You can use [subprocess.run()](https://docs.python.org/3/library/subprocess.html#subprocess.run), it defaults to `check=False` and you can check the error code for success and then use the output. You should also use `text=True` and drop the `str()` below

File: src/scripts/install_machine.py [hunk 3]
```diff
@@ -54,11 +54,35 @@ def get_graphics_capabilies(connection):
...
+
+            if not "lo:" in str(ipv6_loopback):
```
Comment (martinpitt) [inline src/scripts/install_machine.py:66]: Pretty sure you mean "inet6" here? You asked for `lo` already.

File: src/scripts/install_machine.py [hunk 4]
```diff
@@ -54,11 +54,35 @@ def get_graphics_capabilies(connection):
...
+                spice_address = '127.0.0.1'
+        elif subprocess.run(['ifconfig'], shell=True).returncode == 0:
+            ipv6_loopback = subprocess.check_output(['ifconfig', 'lo'])
```
Comment (martinpitt) [inline src/scripts/install_machine.py:69]: Ugh, `ifconfig` -- do you really need that for OpenSUSE? This is so old, I'd really rather not call that as well.

File: src/scripts/install_machine.py [hunk 5]
```diff
@@ -54,11 +54,35 @@ def get_graphics_capabilies(connection):
...
+
+            if not "inet6" in str(ipv6_loopback):
+                spice_address = '127.0.0.1'
+        else:
+            # All previous attempts to find lo assignment have failed
+            # throw an exception and handle this as unrecoverable
+            raise Exception
+    except Exception:
+        # We've unrecoverably failed, lets assume worst case
```
Comment (martinpitt) [inline src/scripts/install_machine.py:78]: No bare `Exception`s, please. If you want to use `check=True`, then catch `subprocess.CalledProcessError`.

File: src/scripts/install_machine.py [hunk 6]
```diff
@@ -54,11 +54,35 @@ def get_graphics_capabilies(connection):
...
+        spice_address = '127.0.0.1'
```
Comment (martinpitt) [inline src/scripts/install_machine.py:79]: This changes the default, and I suppose that's why the [rawhide test fails](https://artifacts.dev.testing-farm.io/25a99126-da33-45da-a19f-0ae964f25e4c/)?

I suggest something like

```py
ip_lo = subprocess.run(ip, ...)
if ip_lo.returncode == 0 and "inet6" in ip_lo.stdout:
    spice_address = "::1"
else:
   spice_address = "127.0.0.1"
```

that's nice and simple.

**Review by martinpitt — CHANGES_REQUESTED** [review]

File: src/scripts/install_machine.py (hunk 2 above)
Comment (SludgeGirl) [reply src/scripts/install_machine.py]: Just got those updated, thanks I'll keep that in mind for future

File: src/scripts/install_machine.py (hunk 3 above)
Comment (SludgeGirl) [reply src/scripts/install_machine.py]: Since we've got the -6 flag, this still works as intended, as if there's no IPv6 assignment lo: wouldn't be displayed since it doesn't show the device if there's no ip assigned, that being said inet6 feels like a better bit of text to search for so I've updated that with this set of changes

**Comment by SludgeGirl** [comment]
I've got this reworked to be inline with your suggestion, let me know if there's any other changes you'd like, thanks for your patience with this one!

**Review by martinpitt — APPROVED** [review]
Thanks, and sorry for the delay! This looks very clean and nice now. Triggered tests.

**Comment by martinpitt** [comment]
Ugh, this [breaks RHEL 8 hard](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1677-fbf43483-20240621-073108-rhel-8-10/log.html). I have a look.

File: src/scripts/install_machine.py [hunk 7]
```diff
@@ -54,11 +54,21 @@ def get_graphics_capabilies(connection):
 
 
 def prepare_graphics_params(connection):
-    graphics_config = {
+    # Check to make sure loopback has an IPv6 address assigned
+    # if not default back to IPv4
+    ip_lo = subprocess.run(['ip', '-6', 'addr', 'show', 'dev', 'lo'], capture_output=True, text=True)
```
Comment (martinpitt) [inline src/scripts/install_machine.py:59]: Ah, haha: This doesn't yet work on Python 3.6:

   TypeError: __init__() got an unexpected keyword argument 'capture_output'"}"

I'll push a fix.

**Review by martinpitt — APPROVED** [review]

File: src/scripts/install_machine.py (hunk 7 above)
Comment (SludgeGirl) [reply src/scripts/install_machine.py]: Ohhhh gotcha, I'll keep that in mind for future and keep a better eye on when features were introduced. Sorry! Bare with me while I'm still getting to grips with it all

**Comment by SludgeGirl** [comment]
Thanks for your help with this!

File: src/scripts/install_machine.py (hunk 7 above)
Comment (martinpitt) [reply src/scripts/install_machine.py]: Don't worry -- this happens to all of us *all the time*. That's why we have tests to tell us where we are wrong :grin:
